# Generated by Django 6.0.1 on 2026-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_until', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_failed_login',
            new_name='lock_time',
        ),
    ]
